#!/bin/sh
PATH=$PATH:/usr/local/netpbm
export PATH
# this is the p6to script used by the VOGLE p6 driver
case "$P6TO" in
	PNG)  ppmtopng > $VOGLE_OUTPUT_FILE.png    # png file
	;;
	TIFF) pnmtotiff > $VOGLE_OUTPUT_FILE.tiff # tiff file
	;;
	XBM) ppmtopgm|pgmtopbm|pbmtoxbm > $VOGLE_OUTPUT_FILE.xbm # greyscale X11 bitmap
	;;
*)
#cat > $$_p6.ppm
cat > $VOGLE_OUTPUT_FILE.ppm
;;
esac
exit

