zap_c.exe: zap_c.c
	cl zap_c.c

F = -FPi87
FFLAGS = -Ox -4Nt -Fa -Fonul -c -AL $(F)

.for.asm:
	fl $(FFLAGS) $*.for
	zap_c < $*.asm > tmp.asm
	del $*.asm
 	ren tmp.asm $*.asm

faxis.asm: faxis.for

fplot.asm: fplot.for

fsadjust.asm: fsadjust.for

flsfit.asm: flsfit.for

fswitch.asm: fswitch.for
