# This file is the same as makefile.bcc except the -ml option
# is removed from CFLAGS.

# NOTE: Borland C++ 1.0 for OS/2 does not compile h2v.exe correctly.
# When h2v.exe runs, it only writes the first font.  It seems that
# this is a bug with Borland's compiler.  GCC compiles this without
# a problem.

CC = bcc

CFLAGS = -w-rvl -DPC -I..\..\src

all: h2v.exe 

h2v.exe: h2v.c getchar.c
    $(CC) $(CFLAGS) h2v.c getchar.c
