#! /bin/sh
#
#/////////////////////////////////////////////////////////
#//
#// interface file for MESCHACH_THREADED
#// 
#/////////////////////////////////////////////////////////
#
MODULE               = meschach_threaded
#
PYTHON_EXTENSION     = $(MODULE).so
SWIG_INTERFACE_FILE  = $(MODULE).i
#
SRC_WRAP = $(MODULE)_wrap.c
OBJ_WRAP = $(SRC_WRAP:.c=.o)
#
SWIG_DEPENDANCIES =  $(SWIG_INTERFACE_FILE) \
SWIG_INTERFACE_M_THREADED_machine.i \
#
#
DYLIBS_LINKED_TO_BUNDLE = $(LIB_MESCHACH_THREADED) \
   $(LIB_MESCHACH)
#
#
TOP = ../..
#
include $(TOP)/PYTHON_EXTENSIONS/python_extension.mk
#
