#
TESTS = cex1.exe cex2.exe cex3.exe

LIB = ..\src\vopl.lib
CFLAGS = -ml -I..\src -DPC

all: $(TESTS)

.c.obj:
	tcc  -c $(CFLAGS) $<

.obj.exe:
	tcc $(CFLAGS) $*.obj $(LIB) vogle.lib

cex1.exe: $(LIB) cex1.obj
	tcc $(CFLAGS) cex1.obj $(LIB) vogle.lib

cex2.exe: $(LIB) cex2.obj
	tcc $(CFLAGS) cex2.obj $(LIB) vogle.lib

cex3.exe: $(LIB) cex3.obj
	tcc $(CFLAGS) cex3.obj $(LIB) vogle.lib

histdemo.exe: $(LIB) histdemo.obj
	tcc $(CFLAGS) histdemo.obj $(LIB) vogle.lib
