F = -FPc

CFLAGS = -AL $(F) -I..\..\vogle\src

.c.obj:
	cl -c $(CFLAGS) $*.c

.obj.exe:
	link /NOE $*.obj,,,..\src\vopl.lib vogle.lib;

cex1.obj: cex1.c

cex1.exe: cex1.obj

cex2.obj: cex2.c

cex2.exe: cex2.obj

cex3.obj: cex3.c

cex3.exe: cex3.obj

histdemo.obj: histdemo.c

histdemo.exe: histdemo.obj
