#include <math.h>
#include <stdio.h>

int main(int argc, char **argv)
{
   FILE *f1 = fopen("gaussP5.txt", "w");   

   double w[16];

   double p[4][16];

   double RAC = sqrt(15.0);
   double D,DD,S;
   int    I,J,K;

   fprintf(f1,"#Generated by gauss.exe \n");

   w[1] = 8./405.0;

   p[1][1]= 0.0;
   p[2][1]= 0.0;
   p[3][1]= 0.0;

   D           = (7. - RAC)/34. ;
   DD          = (13. + 3. * RAC)/34. ;
   S           = (2665. + 14. * RAC)/226800. ;
   J           = 0 ;

e295:
      //continue;

      K             = J + 2 ;
   w[K]      = S;
   p[1][K]   = D;
   p[2][K]   = D;
   p[3][K]   = D;
   K             = J + 3;
   w[K]      = S;
   p[1][K]   = DD;
   p[2][K]   = D;
   p[3][K]   = D;
   K             = J + 4;
   w[K]      = S;
   p[1][K]   = D;
   p[2][K]   = DD;
   p[3][K]   = D;
   K             = J + 5;
   w[K]      = S;
   p[1][K]   = D;
   p[2][K]   = D;
   p[3][K]   = DD;
   //
   if ( J == 4 ) goto e303;
   D  = (7. + RAC) / 34. ;
   DD = (13. - 3. * RAC) / 34. ;
   S  = (2665. - 14. * RAC) / 226800. ;
   J  = 4 ;
   goto e295;
   //
e303:
      //continue;
      D  = (10. - 2 * RAC) / 40. ;
   DD = (10. + 2 * RAC) / 40. ;
   S  = 5. / 567. ;
   //
   for (I=10; I<=15; I++)
   {
      w[I] = S;
   }
   p[1][10] = D;
   p[2][10] = DD;
   p[3][10] = DD;
   p[1][11] = D;
   p[2][11] = D;
   p[3][11] = DD;
   p[1][12] = DD;
   p[2][12] = D;
   p[3][12] = D;
   p[1][13] = DD;
   p[2][13] = DD;
   p[3][13] = D;
   p[1][14] = DD;
   p[2][14] = D;
   p[3][14] = DD;
   p[1][15] = D;
   p[2][15] = DD;
   p[3][15] = D;

   // check
   {
      double sum = 0.0;
      for (I=1; I<=15; I++)
      {
         sum += w[I];
      }
      printf("SUM(w) = %3.18lf = 1/6 (?) \n",sum);
   }


   for (I=1; I<=15; I++)
   {
      fprintf(f1, "%3.20f \n", w[I]);
   }

   fprintf(f1, "p[1][i]\n");
   for (I=1; I<=15; I++)
   {
      fprintf(f1, "%3.20f \n", p[1][I]);
   }
   fprintf(f1, "p[2][i]\n");
   for (I=1; I<=15; I++)
   {
      fprintf(f1, "%3.20f \n", p[2][I]);
   }
   fprintf(f1, "p[3][x]\n");
   for (I=1; I<=15; I++)
   {
      fprintf(f1, "%2.20f \n", p[3][I]);
   }
   /*
      C
    RAC         =SQRT(15.)
    C
    D           = (7. - RAC)/34.
    DD          = (13. + 3. * RAC)/34.
    S           = (2665. + 14. * RAC)/226800.
    J           = 0
    C
    295      CONTINUE
    K             = J + 2
    POTEP5[K]     = S
    COTEP5(1,K)   = D
    COTEP5(2,K)   = D
    COTEP5(3,K)   = D
    K             = J + 3
    POTEP5[K]     = S
    COTEP5(1,K)   = DD
    COTEP5(2,K)   = D
    COTEP5(3,K)   = D
    K             = J + 4
    POTEP5[K]     = S
    COTEP5(1,K)   = D
    COTEP5(2,K)   = DD
    COTEP5(3,K)   = D
    K             = J + 5
    POTEP5[K]     = S
    COTEP5(1,K)   = D
    COTEP5(2,K)   = D
    COTEP5(3,K)   = DD
    C
    IF( J .EQ. 4 ) GOTO 303
    D  = (7. + RAC) / 34.
    DD = (13. - 3. * RAC) / 34.
    S  = (2665. - 14. * RAC) / 226800.
    J  = 4
    GOTO 295
    C
    303 D  = (10. - 2 * RAC) / 40.
    DD = (10. + 2 * RAC) / 40.
    S  = 5. / 567.
    C
    DO 310 I=10,15
    POTEP5(I) = S
    310      CONTINUE
    COTEP5(1,10) = D
    COTEP5(2,10) = DD
    COTEP5(3,10) = DD
    COTEP5(1,11) = D
    COTEP5(2,11) = D
    COTEP5(3,11) = DD
    COTEP5(1,12) = DD
    COTEP5(2,12) = D
    COTEP5(3,12) = D
    COTEP5(1,13) = DD
    COTEP5(2,13) = DD
    COTEP5(3,13) = D
    COTEP5(1,14) = DD
    COTEP5(2,14) = D
    COTEP5(3,14) = DD
    COTEP5(1,15) = D
    COTEP5(2,15) = DD
    COTEP5(3,15) = D
    */

   return 0;
}