CFLAGS = -DPC -ml -I../src -I../../vogle/src

LIB = ..\src\vopl.lib

OBJS = gpp.obj doargs.obj legend.obj read.obj
.c.obj:
	tcc -c $(CFLAGS) $*.c

all: gpp.exe

gpp.obj: gpp.c

doargs.obj: doargs.c

legend.obj: legend.c

read.obj: read.c

gpp.exe: $(OBJS)
	tcc $(CFLAGS) $(OBJS) $(LIB) vogle.lib^M

