CC = bcc

CFLAGS = -DPC -ml -I..\..\src -w-rvl -w-pia
LIB = ..\..\src\vogle.lib

all: h2v.exe hdisp.exe fdisp.exe 

.c.obj:
	$(CC) -c $(CFLAGS) $*.c

h2v.obj: h2v.c h2v.h

getchar.obj: getchar.c

hdisp.obj: hdisp.c

fdisp.obj: fdisp.c

h2v.exe: h2v.c getchar.obj
	$(CC) $(CFLAGS) h2v.c getchar.obj

hdisp.exe: hdisp.c getchar.obj $(LIB)
	$(CC) $(CFLAGS) hdisp.c getchar.obj $(LIB)

fdisp.exe: fdisp.c $(LIB)
	$(CC) $(CFLAGS) fdisp.c $(LIB)

